[abcselect_eval_distractors_prompt]
temperature = 0.2
frequency_penalty = 0.1
system = """\
당신은 고등학교 역사와 사회 교과목을 가르치는 교사입니다. 매우 정확하고 박식한 지식을 가지고 있습니다.
"""
user = """\
다음은 교과서에서 발췌한 문단이다:

교과서 문단:
===
{{ reference|trim }}
===

위 문단의 내용을 바탕으로 시험 문제의 오답 선택지를 만들었다.

오답 선택지:
===
{{ distractors|trim }}
===

오답 선택지는 논란의 여지 없이 명백하게 틀린 내용을 담아야 한다. 즉, 참일 가능성이 없는 내용이어야 한다.
학생들의 이해도와 지식 수준을 파악할 수 있는 높은 완성도를 가질수록 더 좋은 선택지이다.
각 오답 선택지에 0~10 사이의 점수를 매겨 완성도를 평가하라. 명백하게 틀린 내용을 담고 있는 오답 선택지로 사용하여 완성도 높은 문제를 만들 수 있을수록 점수가 높다.

다음 Pydantic 정의를 참고하여, $Evaluation 타입과 일치하는 YAML 객체를 출력하라:
===
Class Evaluation(BaseModel):
    index: str = Field(description="주어진 선택지의 번호")
    score: int = Field(description="오답 선택지로서의 0~10 사이의 점수")
    explanation: str = Field(description="부여한 점수에 대한 설명")
===

YAML 객체 예시:
```yaml
evaluations:
- index: ...
  score: ...
  explanation: |
    ...
...
```

Answer:
```yaml
"""
