[config]
model = "gpt-4o"
default_temperature = 0.2
default_frequency_penalty = 0.1
ai_timeout = 90 # seconds
fallback_models  = []
verbosity_level = 2 # 0,1,2
max_requests_per_minute = 60
max_tokens = 4096
