[difficulty_eval]
model = "gpt-35"
temperature = 0.2
frequency_penalty = 0.1
system = """\
당신은 고등학교 역사와 사회 교과목을 가르치는 교사입니다. 매우 정확하고 박식한 지식을 가지고 있습니다.
"""
user = """\
다음은 고등학교 시험 문제입니다.
문제가 얼마나 어려운지 난이도를 평가해 주세요. 아래 3가지의 사항을 중점적으로 고려해 주세요.
- 문제의 지문이 얼마나 이해하기 어려운지
- 선택지가 있다면, 정답과 다른 선택지가 헷갈리기 쉬운지
- 정답을 맞추기 위해 역사, 사회적 지식이 얼마나 필요한지
난이도를 0~5까지의 수로 평가하고, 이에 대한 자세한 설명을 덧붙여 주세요.
마지막 줄에 난이도를 %%%1%%%과 같은 형식으로 출력해 주세요.
예를 들어, 난이도가 3점이면 %%%3%%%을 마지막 줄에 출력해 주세요.
$$$
{{ problem|trim }}
$$$
"""

