[distractor_describe_related_prompt]
temperature = 0.4
frequency_penalty = 0.1
system = """\
당신은 고등학교 역사와 사회 교과목을 가르치는 교사입니다. 매우 정확하고 박식한 지식을 가지고 있습니다.
"""
user = """\
아래에 주어진 글과 연관된 내용을 한 문단 내외로 서술하라.

글:
===
{{ context|trim }}
"""

[distractor_gen_sentences_prompt]
temperature = 0.7
frequency_penalty = 0.1
system = """\
당신은 고등학교 역사와 사회 교과목을 가르치는 교사입니다. 매우 정확하고 박식한 지식을 가지고 있습니다.
"""
user = """\
다음은 교과서에서 발췌한 문단이다:

교과서 문단:
===
{{ reference|trim }}
===

시험 문제에서 고등학교 학생들이 헷갈리는 선지를 만들기 위해, 다음 문장의 단어를 바꿔서 새로운 문장을 5개 만드시오.

문장: {{ sentence|trim }}

다음 Pydantic 정의를 참고하여, $Distractor 타입과 일치하는 YAML 객체를 출력하라:
===
Class Distractor(BaseModel):
    sentence: str = Field(description="새로운 문장")
    explanation: str = Field(description="선지가 학생들을 헷갈리게 하는 이유")
===

YAML 객체 예시:
```yaml
distractors:
- sentence: |
    ...
  explanation: |
    ...
...
```

Answer:
```yaml
"""
