[extractor_passage_key_sentences_prompt]
model = "gpt-4o"
temperature = 0.4
frequency_penalty = 0.1
system = """\
You are a kind assistant, with professional knowledge in history.
"""
user = """\
다음은 고등학교 역사와 사회 교과서에서 발췌한 글이다:

교과서 글:
===
{{ reference|trim }}
===

위 글에서 핵심 문장을 {{ num_sentences }}개 추출하라. 핵심 문장이란, 역사적인 사건이나 그와 관련된 맥락을 설명하는 온전한 형식의 문장을 뜻한다.

예시:
=====
1587년 6월, 하카타에서 쓰시마 도주 소씨(宗氏) 부자를 만난 도요토미는 조선과의 교섭을 명령했다. 일본이 통일되었다는 사실을 알리고 조선 국왕을 불러와 자신을 알현토록 하라는 내용이었다. 그리고 그 기한을 1588년까지로 못박았다. 또한 불응할 경우에는 조선을 정벌하겠다고 말하였다. 이에 대해 쓰시마 도주는 조선으로부터 거부당할 것이 뻔한 선조의 입조(入朝) 대신 인질과 공물을 요구하자고 제안했지만, 도요토미는 선조의 입조를 고집했다. 결국 쓰시마 도주는 가신인 타치바나 야스히로(橘康廣)를 일본국왕사(日本國王使)로 파견, 일본 국내 사정의 변화를 설명하고 통신사의 파견을 요청하였다. 1587년에 일본 사신은 교섭이 여의치 않으면 병화가 일어날지 모른다고 암시하였다. 하지만 조선 신료들은 ‘교화가 미치지 않는 야만국의 사신을 제대로 접대할 수는 없으며 바닷길이 험해 통신사도 보낼 수 없다’는 답변을 하며 통신사 파견을 거부하였다.
이렇게 도요토미의 첫 번째 외교가 실패하자 그는 1589년 여름까지 조선 국왕을 입조시키라고 쓰시마를 다시 채근했다. 따라서 조선에 1588년 10월과 1589년 6월, 쓰시마에서 두 차례에 사신이 왔다. 1589년 6월엔 신임 쓰시마 도주 소 요시토시는 고니시 유키나가의 사위이며, 대표적인 반전파이기도 했다. 도요토미의 거듭되는 독촉과 조일 양국 충돌 시 겪게될 고통을 우려한 그는 1589년 6월, 하카타 쇼후쿠사(聖福寺)의 승려 겐소와 함께 직접 조선으로 건너와 협상을 진행했다. 그는 쓰시마 도주로서 조선 조정에 통신사를 파견해주도록 다시 간청하면서 바닷길이 험하다면 자신들이 직접 안내하겠다고 나서기까지 했다. 조선과 도요토미 정권 사이에서 살아남기 위한 필사적인 몸부림이었다.

핵심 문장의 예시:
1587년 6월, 하카타에서 쓰시마 도주 소씨(宗氏) 부자를 만난 도요토미는 조선과의 교섭을 명령했다.

해설:
이 문장은 도요토미가 조선과의 교섭에 시도한 첫 번째 사례를 설명하는 문장으로, 당시의 일본과 조선의 외교 관계에 대한 중요한 문장이다.

핵심 문장이 아닌 예시:
조선과 도요토미 정권 사이에서 살아남기 위한 필사적인 몸부림이었다.

해설:
이 문장은 쓰시마 도주의 상황을 설명하는 문장으로, 임진왜란 등 거대한 역사적 사건을 설명하는 맥락에서는 그다지 중요하지 않은 문장이다.
=====

다음 Pydantic 정의를 참고하여, $KeySentence 타입과 일치하는 YAML 객체를 출력하라:
===
Class KeySentence(BaseModel):
    sentence: str = Field(description="핵심 문장")
    keyword: str = Field(description="핵심 문장이 서술하는 주요 키워드")
===

YAML 객체 예시:
```yaml
key_sentences:
- sentence: |
    ...
  keyword: |
    ...
...
```

Answer:
```yaml
"""

[extractor_passage_revise_sentence_prompt]
model = "gpt-4o"
temperature = 0.2
frequency_penalty = 0.1
system = """\
당신은 고등학교 역사와 사회 교과목을 가르치는 교사입니다. 매우 정확하고 박식한 지식을 가지고 있습니다.
"""
user = """\
다음은 교과서에서 발췌한 글이다:

교과서 문단:
===
{{ reference|trim }}
===

다음은 "{{ keyword|trim }}"에 대해 서술하는 핵심 문장이다. 이 문장을 더 명확하게 다듬어 온전한 문장이 되도록 수정하라.

핵심 문장: {{ sentence|trim }}

다음 Pydantic 정의를 참고하여, $RevisedSentence 타입과 일치하는 YAML 객체를 출력하라:
===
Class RevisedSentence(BaseModel):
    sentence: str = Field(description="주어와 서술어, 목적어가 모두 명확하고 불필요한 부사가 없어 단독으로 읽을 수 있는 온전한 문장")
===

YAML 객체 예시:
```yaml
revised_sentence:
- sentence: |
    ...
```

Answer:
```yaml
"""

[extractor_sentence_to_item_prompt]
model = "gpt-4o"
temperature = 0.2
frequency_penalty = 0.1
system = """\
You are a kind assistant, with professional knowledge in history.
"""
user = """\
주어진 문장을 아래와 같이, 사실을 서술하는 문장 형식으로 바꿔 주세요.
문장의 접속사 등을 모두 제거하고, 문장 하나만 읽어도 성립하도록 해 주세요.
하지만 되도록이면 문장의 내용이나 단어는 고치지 마세요.
결과는 반드시 한 문장이어야 하고, '하였다' 형태로 끝나야 합니다.

예시:
보름스 협약이 체결되었다.
성직자 과세 문제로 국왕과 교황이 대립하였다.
성상숭배 문제로 크리스트교 세계가 분열되었다.
위클리프와 후스 등이 교회의 세속화를 비판하였다.
콘스탄츠 공의회가 소집되어 로마 교황의 정통성을 인정하였다.

바꿔야 할 문장은 다음과 같습니다.

문장:
{{ sentence|trim }}
"""
